openapi: 3.0.0
info:
  title: Hamro Pasal API
  version: 1.0.0
  description: REST API for user authentication and profile management
servers:
  - url: http://localhost:5555/api
paths:
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegister'
      responses:
        '201':
          description: User registered
  /auth/login:
    post:
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
      responses:
        '200':
          description: Login successful
components:
  schemas:
    UserRegister:
      type: object
      required: [email, password, firstName, lastName]
      properties:
        email:
          type: string
        password:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        phone:
          type: string
        address:
          type: string
        isAdmin:
          type: boolean
    UserLogin:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
        password:
          type: string
